version: "3.8"

services: 
  api:
    build: 
      context: .
      dockerfile: sentugcagil/Dockerfile
    image: collwr/cagilsntg:latest
    ports: 
      - "3000:80"
  nginx:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf